
name: download catalog & push to rep

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run action 05:05 everyday
  schedule:
  - cron: "5 5 * * *"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    env:
      CATALOG_FILE: catalog.zip
      CATALOG_HTTP: https://flibusta.site/catalog/catalog.zip
      USER_AGENT: "User-Agent: FCI/curl (https://github.com/ablaternae/flibusta-catalog-indexer)"
      # https://flibusta.is/catalog/catalog.zip
      COMMIT_MESSAGE: Update on "$(date +'%Y-%m-%d %H:%M')"
      
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        # working-directory: data

    steps:
    - name: git clone
      run: |
        git clone --single-branch --branch "${INPUTS_BRANCH:-${GITHUB_REF##*/}}" --depth 1 "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" .
        ls -la
    
    - name: git config username
      run: |
          git config user.name "d;)"
          git config user.email "ablaternae@users.noreply.github.com"
          
    - name: download & unzip
      working-directory: ./data
      run: |
        rm -f .updated
        tempname=$(mktemp)
        curl -H "$USER_AGENT" -o "$tempname" "http://flibusta.is/catalog/catalog.zip"
        cmp -s "$tempname" catalog.zip || (rm -f catalog.zip catalog.txt && cp -f "$tempname" catalog.zip && unzip catalog.zip && echo $(date +'%Y-%m-%d %H:%M') > .updated) 

    - name: git push
      run: |
        [ ! -f "./data/.updated" ] && echo "Not that much different from the previous" && exit 0
        COMMIT_MESSAGE="Update on $(date +'%Y-%m-%d %H:%M')"
        git add -A -f ./data
        git status
        git commit -m "$COMMIT_MESSAGE"
        git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        
        
