
name: download catalog & push to rep

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Run action every 4 hour at 05 min
  schedule:
  - cron: "5 */4 * * *"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download:
    env:
      CATALOG_FILE: catalog.zip
      CATALOG_HTTP: https://flibusta.site/catalog/catalog.zip
      USER_AGENT: "User-Agent: FCI/curl (https://github.com/ablaternae/flibusta-catalog-indexer)"
      # https://flibusta.is/catalog/catalog.zip
      COMMIT_MESSAGE: "Update on $(date +'%Y-%m-%d %H:%M')"
      
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        # working-directory: data

    steps:
    - name: git clone
      run: |
        git clone --single-branch --branch "${INPUTS_BRANCH:-${GITHUB_REF##*/}}" --depth 1 "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        ls -la
    
    - name: git config username
      run: |
          git config user.name "d;)"
          git config user.email "ablaternae@users.noreply.github.com"
          
    - name: download & unzip
      working-directory: ./data
      run: |
        tempname=$(mktemp)
        curl -H "$USER_AGENT" -o "$tempname" "http://flibusta.is/catalog/catalog.zip"
        cmp -s "$tempname" catalog.zip || (rm -f catalog.zip catalog.txt && cp -f "$tempname" catalog.zip && unzip catalog.zip && touch .updated) 
        git status
        git add -A
        git status
        [ -f ".updated" ] && echo A || echo NO
        #[ -f ".updated" ] && git add -A || (echo "Not that much different from the previous" && exit 0)
        #git commit -m "$COMMIT_MESSAGE"
        #git push

    - name: git push
      run: |
        ls -la
        ls -la ./data
        [ -f "./data/.updated" ] && git add -A -f ./data || (echo "Not that much different from the previous" && exit 0)
        git status
        git commit -m "$COMMIT_MESSAGE"
        git push
        
