name: cataloguing
on:
  workflow_dispatch:
jobs:
  testphp:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: php
      run: |
        php -f spell.php
        
    #- name: sqlite
    #  run: |
    #    php -r '$db = new SQLite3("test.sqlite"); var_dump( $db->version() );'
    #    php -r '$db = new SQLite3("test.sqlite"); var_dump( $db->query("select sqlite_source_id();")->fetchArray(SQLITE3_ASSOC) );'
    #    php -r '$db = new SQLite3("test.sqlite"); var_dump( $db->query("select sqlite_version();")->fetchArray(SQLITE3_ASSOC) );'
    #    php -r '$db = new SQLite3("test.sqlite"); var_dump( $db->query("PRAGMA user_version;")->fetchArray(SQLITE3_ASSOC) );'
    #    php -r '$db = new SQLite3("test.sqlite"); var_dump( $db->query("PRAGMA schema_version;")->fetchArray(SQLITE3_ASSOC) );'
