name: test
on:
  workflow_dispatch:
jobs:
  testphp:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: version
      run: |
        php -v 
        php -i
    - name: phpinfo
      run: php -r "phpinfo();"
    - name: sqlite
      run: |
        php -r '$db = new SQLite3('test.sqlite'); var_dump( $db );'
