name: test
on:
  workflow_dispatch:
jobs:
  testphp:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: 1
      run: |
        php -v 
        php -i
    - name: phpinfo
      run: php -r "phpinfo();"
